### GET request to get categories
GET http://localhost:8080/api/categories
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

###
POST http://localhost:8080/api/categories
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

Content-Type: application/json

{
  "name": "Category",
  "password": "This is a category"
}